name: Tests

run-name: Test [ ${{ github.run_number }} ] -- Attempt [ ${{github.run_attempt}} ] triggered by @${{ github.actor}}

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
